import Nav from './components/Nav'
import './globals.css'
import { Poiret_One } from 'next/font/google'

const poiretOne = Poiret_One({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
		<html lang="en">
			<body className={`bg-white`}>
				<Nav />
				<div id='bg' className={`${poiretOne.className}`}>{children}</div>
			</body>
		</html>
	);
}
